package com.onboarding.entity;

public enum NotificationType {
    ETAPE_COMPLETE,
    PARCOURS_COMPLETE,
    ASSIGNMENT_COMPLETE,
    ASSIGNMENT_ASSIGNED,
    ASSIGNMENT_OVERDUE,
    CHECKLIST_COMPLETE,
    CHECKLIST_BLOQUEE,
    USER_CREATED,
    USER_UPDATED,
    USER_DELETED,
    SYSTEM_ALERT,
    DEADLINE_REMINDER,
    DOCUMENT_UPLOADED,
    DOCUMENT_MISSING,
    DOCUMENT_SIGNED,
    EVALUATION_RECEIVED,
    MANAGER_NOTIFICATION,
    COLLABORATEUR_NOTIFICATION,
    ADMIN_NOTIFICATION
}
